### ISSUE TITLE
Comment counter en twitter thumbnail lijkt nog niet goed te werken

### ISSUE THREAD

**Issue by linusdm** [wgroeneveld/brainbaking#5]
Wouter, waar ben je? Ik verwacht hier een foto van jou in maatpak...
![Screenshot from 2020-05-16 21-07-50](https://user-images.githubusercontent.com/43893333/82128177-6d7eec80-97b9-11ea-8f75-0a10870eddd0.png)

Er is maar 1 comment, en toch telt hij er 3. Fraude?
![Screenshot from 2020-05-16 21-07-39](https://user-images.githubusercontent.com/43893333/82128178-7079dd00-97b9-11ea-9152-f343eb21a530.png)

**Comment by wgroeneveld** [comment]
Bedankt voor de opmerking Linus! Geen fraude, verwijderde comments worden meegeteld in Commento. 
Dit is een known issue die ik op https://gitlab.com/commento al eens heb teruggevonden, waar er op Brian Baking weinig aan gedaan kan worden (buiten contributen in die repo)!
